name: Deploy Frontend to GCP

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        id: build-push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          build-args: |
            VITE_API_URL=https://ngopiyuk.cciunitel.com/api
            VITE_PHOTO_URL=https://ngopiyuk.cciunitel.com
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ngopiyuk-frontend:latest,${{ secrets.DOCKERHUB_USERNAME }}/ngopiyuk-frontend:${{ github.sha }}

      - name: Deploy to GCP VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/ngopiyuk-production
            docker-compose pull frontend
            docker-compose up -d --no-deps frontend
